In [ ]:
# pip install earthengine-api

Collecting earthengine-api
  Downloading earthengine_api-1.7.47-py3-none-any.whl.metadata (2.2 kB)
Collecting google-cloud-storage (from earthengine-api)
  Downloading google_cloud_storage-3.16.0-py3-none-any.whl.metadata (14 kB)
Collecting google-api-python-client>=2.198.0 (from earthengine-api)
  Downloading google_api_python_client-2.201.0-py3-none-any.whl.metadata (6.8 kB)
Collecting google-auth>=2.58.0 (from earthengine-api)
  Downloading google_auth-2.61.0-py3-none-any.whl.metadata (6.0 kB)
Collecting google-auth-httplib2>=0.4.2 (from earthengine-api)
  Downloading google_auth_httplib2-0.4.4-py3-none-any.whl.metadata (3.0 kB)
Collecting httplib2<1dev,>=0.32.0 (from earthengine-api)
  Downloading httplib2-0.32.0-py3-none-any.whl.metadata (2.2 kB)
Collecting requests (from earthengine-api)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\Users\ASUS\projects\rp_project\J26-DS-314\.venv\Lib\site-packages (from httplib2<1dev,>=0.32.0->earthengine-api) (3.3.3)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5 (from google-api-python-client>=2.198.0->earthengine-api)
  Downloading google_api_core-2.41.0-py3-none-any.whl.metadata (3.2 kB)
Collecting uritemplate<5,>=3.0.1 (from google-api-python-client>=2.198.0->earthengine-api)
  Downloading uritemplate-4.2.0-py3-none-any.whl.metadata (2.6 kB)
Collecting googleapis-common-protos<2.0.0,>=1.69.2 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.198.0->earthengine-api)
  Downloading googleapis_common_protos-1.75.5-py3-none-any.whl.metadata (8.5 kB)
Collecting protobuf<8.0.0,>=6.33.5 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.198.0->earthengine-api)
  Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting proto-plus<2.0.0,>=1.26.1 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.198.0->earthengine-api)
  Downloading proto_plus-1.29.0-py3-none-any.whl.metadata (2.2 kB)
Collecting opentelemetry-api<2.0.0,>=1.44.0 (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.198.0->earthengine-api)
  Downloading opentelemetry_api-1.45.1-py3-none-any.whl.metadata (1.4 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth>=2.58.0->earthengine-api)
  Downloading pyasn1_modules-0.4.2-py3-none-any.whl.metadata (3.5 kB)
Collecting cryptography>=38.0.3 (from google-auth>=2.58.0->earthengine-api)
  Downloading cryptography-50.0.2-cp311-abi3-win_amd64.whl.metadata (4.4 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\Users\ASUS\projects\rp_project\J26-DS-314\.venv\Lib\site-packages (from opentelemetry-api<2.0.0,>=1.44.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0,>=1.31.5->google-api-python-client>=2.198.0->earthengine-api) (4.16.0)
Collecting charset_normalizer<4,>=2 (from requests->earthengine-api)
  Downloading charset_normalizer-3.5.2-cp311-cp311-win_amd64.whl.metadata (47 kB)
Collecting idna<4,>=2.5 (from requests->earthengine-api)
  Downloading idna-3.20-py3-none-any.whl.metadata (7.2 kB)
Collecting urllib3<3,>=1.26 (from requests->earthengine-api)
  Downloading urllib3-2.8.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: certifi>=2023.5.7 in c:\Users\ASUS\projects\rp_project\J26-DS-314\.venv\Lib\site-packages (from requests->earthengine-api) (2026.7.22)
Collecting cffi>=2.0.0 (from cryptography>=38.0.3->google-auth>=2.58.0->earthengine-api)
  Downloading cffi-2.1.1-cp311-cp311-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=2.58.0->earthengine-api)
  Downloading pycparser-3.0-py3-none-any.whl.metadata (8.2 kB)
Collecting pyasn1<0.7.0,>=0.6.1 (from pyasn1-modules>=0.2.1->google-auth>=2.58.0->earthengine-api)
  Downloading pyasn1-0.6.4-py3-none-any.whl.metadata (8.4 kB)
Collecting google-cloud-core<3.0.0,>=2.4.2 (from google-cloud-storage->earthengine-api)
  Downloading google_cloud_core-2.8.0-py3-none-any.whl.metadata (2.9 kB)
Collecting google-resumable-media<3.0.0,>=2.7.2 (from google-cloud-storage->earthengine-api)
  Downloading google_resumable_media-2.11.0-py3-none-any.whl.metadata (2.3 kB)
Collecting google-crc32c<2.0.0,>=1.6.0 (from google-cloud-storage->earthengine-api)
  Downloading google_crc32c-1.9.0-cp311-cp311-win_amd64.whl.metadata (2.2 kB)
Downloading earthengine_api-1.7.47-py3-none-any.whl (482 kB)
Downloading httplib2-0.32.0-py3-none-any.whl (93 kB)
Downloading google_api_python_client-2.201.0-py3-none-any.whl (16.8 MB)
   ---------------------------------------- 0.0/16.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.8 MB ? eta -:--:--
    --------------------------------------- 0.3/16.8 MB ? eta -:--:--
    --------------------------------------- 0.3/16.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.8 MB 730.2 kB/s eta 0:00:23
   - -------------------------------------- 0.5/16.8 MB 730.2 kB/s eta 0:00:23
   - -------------------------------------- 0.8/16.8 MB 699.0 kB/s eta 0:00:23
   - -------------------------------------- 0.8/16.8 MB 699.0 kB/s eta 0:00:23
   -- ------------------------------------- 1.0/16.8 MB 680.3 kB/s eta 0:00:24
   --- ------------------------------------ 1.3/16.8 MB 684.9 kB/s eta 0:00:23
   --- ------------------------------------ 1.3/16.8 MB 684.9 kB/s eta 0:00:23
   --- ------------------------------------ 1.6/16.8 MB 671.1 kB/s eta 0:00:23
   --- ------------------------------------ 1.6/16.8 MB 671.1 kB/s eta 0:00:23
   ---- ----------------------------------- 1.8/16.8 MB 666.8 kB/s eta 0:00:23
   ---- ----------------------------------- 1.8/16.8 MB 666.8 kB/s eta 0:00:23
   ---- ----------------------------------- 2.1/16.8 MB 663.7 kB/s eta 0:00:23
   ---- ----------------------------------- 2.1/16.8 MB 663.7 kB/s eta 0:00:23
   ----- ---------------------------------- 2.4/16.8 MB 658.0 kB/s eta 0:00:22
   ----- ---------------------------------- 2.4/16.8 MB 658.0 kB/s eta 0:00:22
   ----- ---------------------------------- 2.4/16.8 MB 658.0 kB/s eta 0:00:22
   ------ --------------------------------- 2.6/16.8 MB 618.9 kB/s eta 0:00:23
   ------ --------------------------------- 2.6/16.8 MB 618.9 kB/s eta 0:00:23
   ------ --------------------------------- 2.9/16.8 MB 612.3 kB/s eta 0:00:23
   ------ --------------------------------- 2.9/16.8 MB 612.3 kB/s eta 0:00:23
   ------ --------------------------------- 2.9/16.8 MB 612.3 kB/s eta 0:00:23
   ------- -------------------------------- 3.1/16.8 MB 580.3 kB/s eta 0:00:24
   ------- -------------------------------- 3.1/16.8 MB 580.3 kB/s eta 0:00:24
   ------- -------------------------------- 3.1/16.8 MB 580.3 kB/s eta 0:00:24
   ------- -------------------------------- 3.1/16.8 MB 580.3 kB/s eta 0:00:24
   -------- ------------------------------- 3.4/16.8 MB 542.6 kB/s eta 0:00:25
   -------- ------------------------------- 3.4/16.8 MB 542.6 kB/s eta 0:00:25
   -------- ------------------------------- 3.4/16.8 MB 542.6 kB/s eta 0:00:25
   -------- ------------------------------- 3.4/16.8 MB 542.6 kB/s eta 0:00:25
   -------- ------------------------------- 3.7/16.8 MB 509.6 kB/s eta 0:00:26
   -------- ------------------------------- 3.7/16.8 MB 509.6 kB/s eta 0:00:26
   -------- ------------------------------- 3.7/16.8 MB 509.6 kB/s eta 0:00:26
   --------- ------------------------------ 3.9/16.8 MB 510.6 kB/s eta 0:00:26
   --------- ------------------------------ 3.9/16.8 MB 510.6 kB/s eta 0:00:26
   --------- ------------------------------ 4.2/16.8 MB 514.7 kB/s eta 0:00:25
   --------- ------------------------------ 4.2/16.8 MB 514.7 kB/s eta 0:00:25
   ---------- ----------------------------- 4.5/16.8 MB 521.2 kB/s eta 0:00:24
   ---------- ----------------------------- 4.5/16.8 MB 521.2 kB/s eta 0:00:24
   ---------- ----------------------------- 4.5/16.8 MB 521.2 kB/s eta 0:00:24
   ----------- ---------------------------- 4.7/16.8 MB 514.8 kB/s eta 0:00:24
   ----------- ---------------------------- 4.7/16.8 MB 514.8 kB/s eta 0:00:24
   ----------- ---------------------------- 4.7/16.8 MB 514.8 kB/s eta 0:00:24
   ----------- ---------------------------- 4.7/16.8 MB 514.8 kB/s eta 0:00:24
   ----------- ---------------------------- 5.0/16.8 MB 495.1 kB/s eta 0:00:24
   ----------- ---------------------------- 5.0/16.8 MB 495.1 kB/s eta 0:00:24
   ------------ --------------------------- 5.2/16.8 MB 491.9 kB/s eta 0:00:24
   ------------ --------------------------- 5.2/16.8 MB 491.9 kB/s eta 0:00:24
   ------------ --------------------------- 5.2/16.8 MB 491.9 kB/s eta 0:00:24
   ------------- -------------------------- 5.5/16.8 MB 489.1 kB/s eta 0:00:24
   ------------- -------------------------- 5.5/16.8 MB 489.1 kB/s eta 0:00:24
   ------------- -------------------------- 5.5/16.8 MB 489.1 kB/s eta 0:00:24
   ------------- -------------------------- 5.8/16.8 MB 487.3 kB/s eta 0:00:23
   ------------- -------------------------- 5.8/16.8 MB 487.3 kB/s eta 0:00:23
   -------------- ------------------------- 6.0/16.8 MB 490.2 kB/s eta 0:00:22
   -------------- ------------------------- 6.0/16.8 MB 490.2 kB/s eta 0:00:22
   -------------- ------------------------- 6.3/16.8 MB 495.3 kB/s eta 0:00:22
   -------------- ------------------------- 6.3/16.8 MB 495.3 kB/s eta 0:00:22
   --------------- ------------------------ 6.6/16.8 MB 500.2 kB/s eta 0:00:21
   ---------------- ----------------------- 6.8/16.8 MB 507.8 kB/s eta 0:00:20
   ---------------- ----------------------- 6.8/16.8 MB 507.8 kB/s eta 0:00:20
   ---------------- ----------------------- 6.8/16.8 MB 507.8 kB/s eta 0:00:20
   ---------------- ----------------------- 7.1/16.8 MB 504.9 kB/s eta 0:00:20
   ---------------- ----------------------- 7.1/16.8 MB 504.9 kB/s eta 0:00:20
   ----------------- ---------------------- 7.3/16.8 MB 507.3 kB/s eta 0:00:19
   ----------------- ---------------------- 7.3/16.8 MB 507.3 kB/s eta 0:00:19
   ----------------- ---------------------- 7.3/16.8 MB 507.3 kB/s eta 0:00:19
   ------------------ --------------------- 7.6/16.8 MB 501.9 kB/s eta 0:00:19
   ------------------ --------------------- 7.6/16.8 MB 501.9 kB/s eta 0:00:19
   ------------------ --------------------- 7.6/16.8 MB 501.9 kB/s eta 0:00:19
   ------------------ --------------------- 7.9/16.8 MB 501.6 kB/s eta 0:00:18
   ------------------ --------------------- 7.9/16.8 MB 501.6 kB/s eta 0:00:18
   ------------------- -------------------- 8.1/16.8 MB 501.8 kB/s eta 0:00:18
   ------------------- -------------------- 8.1/16.8 MB 501.8 kB/s eta 0:00:18
   ------------------- -------------------- 8.1/16.8 MB 501.8 kB/s eta 0:00:18
   ------------------- -------------------- 8.4/16.8 MB 502.0 kB/s eta 0:00:17
   ------------------- -------------------- 8.4/16.8 MB 502.0 kB/s eta 0:00:17
   -------------------- ------------------- 8.7/16.8 MB 504.6 kB/s eta 0:00:17
   --------------------- ------------------ 8.9/16.8 MB 510.8 kB/s eta 0:00:16
   --------------------- ------------------ 8.9/16.8 MB 510.8 kB/s eta 0:00:16
   --------------------- ------------------ 9.2/16.8 MB 513.0 kB/s eta 0:00:15
   ---------------------- ----------------- 9.4/16.8 MB 519.7 kB/s eta 0:00:15
   ---------------------- ----------------- 9.4/16.8 MB 519.7 kB/s eta 0:00:15
   ----------------------- ---------------- 9.7/16.8 MB 527.0 kB/s eta 0:00:14
   ----------------------- ---------------- 10.0/16.8 MB 532.8 kB/s eta 0:00:13
   ------------------------ --------------- 10.2/16.8 MB 537.6 kB/s eta 0:00:13
   ------------------------ --------------- 10.2/16.8 MB 537.6 kB/s eta 0:00:13
   ------------------------ --------------- 10.5/16.8 MB 541.6 kB/s eta 0:00:12
   ------------------------- -------------- 10.7/16.8 MB 549.2 kB/s eta 0:00:12
   -------------------------- ------------- 11.0/16.8 MB 554.3 kB/s eta 0:00:11
   -------------------------- ------------- 11.0/16.8 MB 554.3 kB/s eta 0:00:11
   -------------------------- ------------- 11.3/16.8 MB 559.7 kB/s eta 0:00:10
   --------------------------- ------------ 11.5/16.8 MB 564.5 kB/s eta 0:00:10
   --------------------------- ------------ 11.5/16.8 MB 564.5 kB/s eta 0:00:10
   ---------------------------- ----------- 11.8/16.8 MB 567.9 kB/s eta 0:00:09
   ---------------------------- ----------- 11.8/16.8 MB 567.9 kB/s eta 0:00:09
   ---------------------------- ----------- 12.1/16.8 MB 569.8 kB/s eta 0:00:09
   ----------------------------- ---------- 12.3/16.8 MB 572.5 kB/s eta 0:00:08
   ----------------------------- ---------- 12.3/16.8 MB 572.5 kB/s eta 0:00:08
   ----------------------------- ---------- 12.6/16.8 MB 573.9 kB/s eta 0:00:08
   ------------------------------ --------- 12.8/16.8 MB 579.4 kB/s eta 0:00:07
   ------------------------------ --------- 12.8/16.8 MB 579.4 kB/s eta 0:00:07
   ------------------------------- -------- 13.1/16.8 MB 583.5 kB/s eta 0:00:07
   ------------------------------- -------- 13.4/16.8 MB 588.7 kB/s eta 0:00:06
   -------------------------------- ------- 13.6/16.8 MB 590.9 kB/s eta 0:00:06
   -------------------------------- ------- 13.6/16.8 MB 590.9 kB/s eta 0:00:06
   --------------------------------- ------ 13.9/16.8 MB 593.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.8 MB 593.1 kB/s eta 0:00:05
   --------------------------------- ------ 14.2/16.8 MB 594.4 kB/s eta 0:00:05
   --------------------------------- ------ 14.2/16.8 MB 594.4 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.8 MB 596.8 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.8 MB 596.8 kB/s eta 0:00:05
   ---------------------------------- ----- 14.7/16.8 MB 595.7 kB/s eta 0:00:04
   ---------------------------------- ----- 14.7/16.8 MB 595.7 kB/s eta 0:00:04
   ----------------------------------- ---- 14.9/16.8 MB 595.8 kB/s eta 0:00:04
   ----------------------------------- ---- 14.9/16.8 MB 595.8 kB/s eta 0:00:04
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.8 MB 596.6 kB/s eta 0:00:03
   ------------------------------------ --- 15.5/16.8 MB 565.7 kB/s eta 0:00:03
   ------------------------------------- -- 15.7/16.8 MB 571.8 kB/s eta 0:00:02
   -------------------------------------- - 16.0/16.8 MB 579.2 kB/s eta 0:00:02
   -------------------------------------- - 16.3/16.8 MB 583.8 kB/s eta 0:00:01
   ---------------------------------------  16.5/16.8 MB 588.7 kB/s eta 0:00:01
   ---------------------------------------- 16.8/16.8 MB 593.1 kB/s  0:00:28
Downloading google_api_core-2.41.0-py3-none-any.whl (215 kB)
Downloading google_auth-2.61.0-py3-none-any.whl (268 kB)
Downloading google_auth_httplib2-0.4.4-py3-none-any.whl (9.5 kB)
Downloading googleapis_common_protos-1.75.5-py3-none-any.whl (307 kB)
Downloading opentelemetry_api-1.45.1-py3-none-any.whl (60 kB)
Downloading proto_plus-1.29.0-py3-none-any.whl (50 kB)
Downloading protobuf-7.36.2-cp310-abi3-win_amd64.whl (456 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.5.2-cp311-cp311-win_amd64.whl (214 kB)
Downloading idna-3.20-py3-none-any.whl (69 kB)
Downloading uritemplate-4.2.0-py3-none-any.whl (11 kB)
Downloading urllib3-2.8.0-py3-none-any.whl (135 kB)
Downloading cryptography-50.0.2-cp311-abi3-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   -- ------------------------------------- 0.3/3.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.8 MB 1.9 MB/s eta 0:00:02
   -------- ------------------------------- 0.8/3.8 MB 1.4 MB/s eta 0:00:03
   ---------- ----------------------------- 1.0/3.8 MB 1.6 MB/s eta 0:00:02
   ------------- -------------------------- 1.3/3.8 MB 1.5 MB/s eta 0:00:02
   ---------------- ----------------------- 1.6/3.8 MB 1.3 MB/s eta 0:00:02
   --------------------- ------------------ 2.1/3.8 MB 1.4 MB/s eta 0:00:02
   ------------------------ --------------- 2.4/3.8 MB 1.4 MB/s eta 0:00:02
   --------------------------- ------------ 2.6/3.8 MB 1.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 1.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.9/3.8 MB 1.4 MB/s eta 0:00:01
   ----------------------------------- ---- 3.4/3.8 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 1.4 MB/s  0:00:02
Downloading cffi-2.1.1-cp311-cp311-win_amd64.whl (185 kB)
Downloading pyasn1_modules-0.4.2-py3-none-any.whl (181 kB)
Downloading pyasn1-0.6.4-py3-none-any.whl (84 kB)
Downloading google_cloud_storage-3.16.0-py3-none-any.whl (343 kB)
Downloading google_cloud_core-2.8.0-py3-none-any.whl (31 kB)
Downloading google_crc32c-1.9.0-cp311-cp311-win_amd64.whl (35 kB)
Downloading google_resumable_media-2.11.0-py3-none-any.whl (81 kB)
Downloading pycparser-3.0-py3-none-any.whl (48 kB)
Installing collected packages: urllib3, uritemplate, pycparser, pyasn1, protobuf, opentelemetry-api, idna, httplib2, google-crc32c, charset_normalizer, requests, pyasn1-modules, proto-plus, googleapis-common-protos, google-resumable-media, cffi, cryptography, google-auth, google-auth-httplib2, google-api-core, google-cloud-core, google-api-python-client, google-cloud-storage, earthengine-api

   --- ------------------------------------  2/24 [pycparser]
   ------ ---------------------------------  4/24 [protobuf]
   -------- -------------------------------  5/24 [opentelemetry-api]
   ----------- ----------------------------  7/24 [httplib2]
   ------------------ --------------------- 11/24 [pyasn1-modules]
   ------------------ --------------------- 11/24 [pyasn1-modules]
   -------------------- ------------------- 12/24 [proto-plus]
   --------------------- ------------------ 13/24 [googleapis-common-protos]
   ----------------------- ---------------- 14/24 [google-resumable-media]
   -------------------------- ------------- 16/24 [cryptography]
   -------------------------- ------------- 16/24 [cryptography]
   ---------------------------- ----------- 17/24 [google-auth]
   ------------------------------- -------- 19/24 [google-api-core]
   --------------------------------- ------ 20/24 [google-cloud-core]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ----------------------------------- ---- 21/24 [google-api-python-client]
   ------------------------------------ --- 22/24 [google-cloud-storage]
   ------------------------------------ --- 22/24 [google-cloud-storage]
   -------------------------------------- - 23/24 [earthengine-api]
   -------------------------------------- - 23/24 [earthengine-api]
   -------------------------------------- - 23/24 [earthengine-api]

In [1]:
import ee
import pandas as pd

In [3]:
ee.Authenticate()

Successfully saved authorization token.

In [4]:
ee.Initialize(project='multimodal-flood-risk')

print("Earth Engine initialized successfully.")

*** Earth Engine *** Share your feedback by taking our Annual Developer Satisfaction Survey: https://google.qualtrics.com/jfe/form/SV_9oS0DRcPvElRMNw?source=python

Earth Engine initialized successfully.

## Define the 2 areas

In [5]:
# ------------------------------------------------------------
# PP1 Candidate AOI
# ------------------------------------------------------------

candidate_aoi = ee.Geometry.Rectangle([
    79.82,   # west
    6.80,    # south
    80.28,   # east
    7.25     # north
])


# ------------------------------------------------------------
# Small technical pilot AOI
# ------------------------------------------------------------

pilot_aoi = ee.Geometry.Rectangle([
    80.055,  # west
    6.885,  # south
    80.105, # east
    6.935   # north
])


print(
    "Candidate AOI area (km²):",
    candidate_aoi.area(1).divide(1_000_000).getInfo()
)

print(
    "Hanwella pilot area (km²):",
    pilot_aoi.area(1).divide(1_000_000).getInfo()
)

Candidate AOI area (km²): 2540.210940965659
Hanwella pilot area (km²): 30.686324537958345

## Defining the EV2 search window

In [6]:
SEARCH_START = '2025-11-20'
SEARCH_END = '2025-12-24'

print("Sentinel-1 search window:")
print(SEARCH_START, "to", SEARCH_END)

Sentinel-1 search window:
2025-11-20 to 2025-12-24

## Retrieving Sentinel-1

In [7]:
s1_collection = (
    ee.ImageCollection('COPERNICUS/S1_GRD')
    .filterBounds(candidate_aoi)
    .filterDate(SEARCH_START, SEARCH_END)
    .filter(ee.Filter.eq('instrumentMode', 'IW'))
    .filter(
        ee.Filter.listContains(
            'transmitterReceiverPolarisation',
            'VV'
        )
    )
    .filter(
        ee.Filter.listContains(
            'transmitterReceiverPolarisation',
            'VH'
        )
    )
    .sort('system:time_start')
)

s1_count = s1_collection.size().getInfo()

print("Number of Sentinel-1 candidate scenes:", s1_count)

Number of Sentinel-1 candidate scenes: 14

## Sentinel‑1 Metadata Inventory

In [8]:
def extract_s1_metadata(image):
    """
    Extract the metadata needed for PP1 Sentinel-1
    acquisition screening.
    """

    acquisition_time = ee.Date(
        image.get('system:time_start')
    )

    intersection_area = (
        image.geometry()
        .intersection(candidate_aoi, 1)
        .area(1)
    )

    candidate_area = candidate_aoi.area(1)

    coverage_percent = (
        intersection_area
        .divide(candidate_area)
        .multiply(100)
    )

    return ee.Feature(None, {

        'scene_id':
            image.get('system:index'),

        'asset_id':
            image.id(),

        'acquisition_utc':
            acquisition_time.format(
                'yyyy-MM-dd HH:mm',
                'UTC'
            ),

        'acquisition_local':
            acquisition_time.format(
                'yyyy-MM-dd HH:mm',
                'Asia/Colombo'
            ),

        'platform':
            image.get('platform_number'),

        'orbit_pass':
            image.get(
                'orbitProperties_pass'
            ),

        'relative_orbit':
            image.get(
                'relativeOrbitNumber_start'
            ),

        'instrument_mode':
            image.get(
                'instrumentMode'
            ),

        'polarization':
            ee.List(
                image.get(
                    'transmitterReceiverPolarisation'
                )
            ).join(','),

        'resolution_m':
            image.get(
                'resolution_meters'
            ),

        'slice_number':
            image.get(
                'sliceNumber'
            ),

        'total_slices':
            image.get(
                'totalSlices'
            ),

        'coverage_percent':
            coverage_percent

    })

In [9]:
inventory_fc = ee.FeatureCollection(
    s1_collection.map(extract_s1_metadata)
)

inventory_data = inventory_fc.getInfo()

rows = [
    feature['properties']
    for feature in inventory_data['features']
]

inventory_df = pd.DataFrame(rows)

inventory_df

,acquisition_local,acquisition_utc,asset_id,coverage_percent,instrument_mode,orbit_pass,platform,polarization,relative_orbit,resolution_m,scene_id,slice_number,total_slices
0,2025-11-26 05:55,2025-11-26 00:25,S1A_IW_GRDH_1SDV_20251126T002515_20251126T0025...,56.693060,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251126T002515_20251126T0025...,2,3
1,2025-11-26 05:55,2025-11-26 00:25,S1A_IW_GRDH_1SDV_20251126T002540_20251126T0026...,43.373912,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251126T002540_20251126T0026...,3,3
2,2025-11-26 18:19,2025-11-26 12:49,S1A_IW_GRDH_1SDV_20251126T124916_20251126T1249...,6.576538,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251126T124916_20251126T1249...,1,3
3,2025-11-26 18:19,2025-11-26 12:49,S1A_IW_GRDH_1SDV_20251126T124945_20251126T1250...,3.084946,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251126T124945_20251126T1250...,2,3
4,2025-12-02 05:54,2025-12-02 00:24,S1C_IW_GRDH_1SDV_20251202T002429_20251202T0024...,100.000000,IW,DESCENDING,C,"VV,VH",19,10,S1C_IW_GRDH_1SDV_20251202T002429_20251202T0024...,3,4
5,2025-12-02 18:18,2025-12-02 12:48,S1C_IW_GRDH_1SDV_20251202T124832_20251202T1248...,9.728797,IW,ASCENDING,C,"VV,VH",27,10,S1C_IW_GRDH_1SDV_20251202T124832_20251202T1248...,2,6
6,2025-12-08 05:55,2025-12-08 00:25,S1A_IW_GRDH_1SDV_20251208T002514_20251208T0025...,56.733736,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251208T002514_20251208T0025...,2,3
7,2025-12-08 05:55,2025-12-08 00:25,S1A_IW_GRDH_1SDV_20251208T002539_20251208T0026...,43.333318,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251208T002539_20251208T0026...,3,3
8,2025-12-08 18:19,2025-12-08 12:49,S1A_IW_GRDH_1SDV_20251208T124915_20251208T1249...,6.686733,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251208T124915_20251208T1249...,1,3
9,2025-12-08 18:19,2025-12-08 12:49,S1A_IW_GRDH_1SDV_20251208T124944_20251208T1250...,3.108311,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251208T124944_20251208T1250...,2,3
10,2025-12-20 05:55,2025-12-20 00:25,S1A_IW_GRDH_1SDV_20251220T002512_20251220T0025...,56.707925,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251220T002512_20251220T0025...,2,3
11,2025-12-20 05:55,2025-12-20 00:25,S1A_IW_GRDH_1SDV_20251220T002537_20251220T0026...,43.358778,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251220T002537_20251220T0026...,3,3
12,2025-12-20 18:19,2025-12-20 12:49,S1A_IW_GRDH_1SDV_20251220T124913_20251220T1249...,6.544987,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251220T124913_20251220T1249...,1,3
13,2025-12-20 18:19,2025-12-20 12:49,S1A_IW_GRDH_1SDV_20251220T124942_20251220T1250...,3.085749,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251220T124942_20251220T1250...,2,3

In [10]:
inventory_df = inventory_df.sort_values(
    'acquisition_local'
).reset_index(drop=True)

inventory_df

,acquisition_local,acquisition_utc,asset_id,coverage_percent,instrument_mode,orbit_pass,platform,polarization,relative_orbit,resolution_m,scene_id,slice_number,total_slices
0,2025-11-26 05:55,2025-11-26 00:25,S1A_IW_GRDH_1SDV_20251126T002515_20251126T0025...,56.693060,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251126T002515_20251126T0025...,2,3
1,2025-11-26 05:55,2025-11-26 00:25,S1A_IW_GRDH_1SDV_20251126T002540_20251126T0026...,43.373912,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251126T002540_20251126T0026...,3,3
2,2025-11-26 18:19,2025-11-26 12:49,S1A_IW_GRDH_1SDV_20251126T124916_20251126T1249...,6.576538,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251126T124916_20251126T1249...,1,3
3,2025-11-26 18:19,2025-11-26 12:49,S1A_IW_GRDH_1SDV_20251126T124945_20251126T1250...,3.084946,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251126T124945_20251126T1250...,2,3
4,2025-12-02 05:54,2025-12-02 00:24,S1C_IW_GRDH_1SDV_20251202T002429_20251202T0024...,100.000000,IW,DESCENDING,C,"VV,VH",19,10,S1C_IW_GRDH_1SDV_20251202T002429_20251202T0024...,3,4
5,2025-12-02 18:18,2025-12-02 12:48,S1C_IW_GRDH_1SDV_20251202T124832_20251202T1248...,9.728797,IW,ASCENDING,C,"VV,VH",27,10,S1C_IW_GRDH_1SDV_20251202T124832_20251202T1248...,2,6
6,2025-12-08 05:55,2025-12-08 00:25,S1A_IW_GRDH_1SDV_20251208T002514_20251208T0025...,56.733736,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251208T002514_20251208T0025...,2,3
7,2025-12-08 05:55,2025-12-08 00:25,S1A_IW_GRDH_1SDV_20251208T002539_20251208T0026...,43.333318,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251208T002539_20251208T0026...,3,3
8,2025-12-08 18:19,2025-12-08 12:49,S1A_IW_GRDH_1SDV_20251208T124915_20251208T1249...,6.686733,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251208T124915_20251208T1249...,1,3
9,2025-12-08 18:19,2025-12-08 12:49,S1A_IW_GRDH_1SDV_20251208T124944_20251208T1250...,3.108311,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251208T124944_20251208T1250...,2,3
10,2025-12-20 05:55,2025-12-20 00:25,S1A_IW_GRDH_1SDV_20251220T002512_20251220T0025...,56.707925,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251220T002512_20251220T0025...,2,3
11,2025-12-20 05:55,2025-12-20 00:25,S1A_IW_GRDH_1SDV_20251220T002537_20251220T0026...,43.358778,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251220T002537_20251220T0026...,3,3
12,2025-12-20 18:19,2025-12-20 12:49,S1A_IW_GRDH_1SDV_20251220T124913_20251220T1249...,6.544987,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251220T124913_20251220T1249...,1,3
13,2025-12-20 18:19,2025-12-20 12:49,S1A_IW_GRDH_1SDV_20251220T124942_20251220T1250...,3.085749,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251220T124942_20251220T1250...,2,3

In [11]:
inventory_df[
    [
        'scene_id',
        'acquisition_local',
        'platform',
        'orbit_pass',
        'relative_orbit',
        'instrument_mode',
        'polarization',
        'coverage_percent'
    ]
]

,scene_id,acquisition_local,platform,orbit_pass,relative_orbit,instrument_mode,polarization,coverage_percent
0,S1A_IW_GRDH_1SDV_20251126T002515_20251126T0025...,2025-11-26 05:55,A,DESCENDING,19,IW,"VV,VH",56.693060
1,S1A_IW_GRDH_1SDV_20251126T002540_20251126T0026...,2025-11-26 05:55,A,DESCENDING,19,IW,"VV,VH",43.373912
2,S1A_IW_GRDH_1SDV_20251126T124916_20251126T1249...,2025-11-26 18:19,A,ASCENDING,27,IW,"VV,VH",6.576538
3,S1A_IW_GRDH_1SDV_20251126T124945_20251126T1250...,2025-11-26 18:19,A,ASCENDING,27,IW,"VV,VH",3.084946
4,S1C_IW_GRDH_1SDV_20251202T002429_20251202T0024...,2025-12-02 05:54,C,DESCENDING,19,IW,"VV,VH",100.000000
5,S1C_IW_GRDH_1SDV_20251202T124832_20251202T1248...,2025-12-02 18:18,C,ASCENDING,27,IW,"VV,VH",9.728797
6,S1A_IW_GRDH_1SDV_20251208T002514_20251208T0025...,2025-12-08 05:55,A,DESCENDING,19,IW,"VV,VH",56.733736
7,S1A_IW_GRDH_1SDV_20251208T002539_20251208T0026...,2025-12-08 05:55,A,DESCENDING,19,IW,"VV,VH",43.333318
8,S1A_IW_GRDH_1SDV_20251208T124915_20251208T1249...,2025-12-08 18:19,A,ASCENDING,27,IW,"VV,VH",6.686733
9,S1A_IW_GRDH_1SDV_20251208T124944_20251208T1250...,2025-12-08 18:19,A,ASCENDING,27,IW,"VV,VH",3.108311
10,S1A_IW_GRDH_1SDV_20251220T002512_20251220T0025...,2025-12-20 05:55,A,DESCENDING,19,IW,"VV,VH",56.707925
11,S1A_IW_GRDH_1SDV_20251220T002537_20251220T0026...,2025-12-20 05:55,A,DESCENDING,19,IW,"VV,VH",43.358778
12,S1A_IW_GRDH_1SDV_20251220T124913_20251220T1249...,2025-12-20 18:19,A,ASCENDING,27,IW,"VV,VH",6.544987
13,S1A_IW_GRDH_1SDV_20251220T124942_20251220T1250...,2025-12-20 18:19,A,ASCENDING,27,IW,"VV,VH",3.085749

In [12]:
inventory_df.insert(
    0,
    'event_id',
    'EV2_Nov_2025'
)

inventory_df.insert(
    1,
    'aoi_id',
    'PP1_AOI_KELANI_01'
)

inventory_df

,event_id,aoi_id,acquisition_local,acquisition_utc,asset_id,coverage_percent,instrument_mode,orbit_pass,platform,polarization,relative_orbit,resolution_m,scene_id,slice_number,total_slices
0,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-11-26 05:55,2025-11-26 00:25,S1A_IW_GRDH_1SDV_20251126T002515_20251126T0025...,56.693060,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251126T002515_20251126T0025...,2,3
1,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-11-26 05:55,2025-11-26 00:25,S1A_IW_GRDH_1SDV_20251126T002540_20251126T0026...,43.373912,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251126T002540_20251126T0026...,3,3
2,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-11-26 18:19,2025-11-26 12:49,S1A_IW_GRDH_1SDV_20251126T124916_20251126T1249...,6.576538,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251126T124916_20251126T1249...,1,3
3,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-11-26 18:19,2025-11-26 12:49,S1A_IW_GRDH_1SDV_20251126T124945_20251126T1250...,3.084946,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251126T124945_20251126T1250...,2,3
4,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-02 05:54,2025-12-02 00:24,S1C_IW_GRDH_1SDV_20251202T002429_20251202T0024...,100.000000,IW,DESCENDING,C,"VV,VH",19,10,S1C_IW_GRDH_1SDV_20251202T002429_20251202T0024...,3,4
5,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-02 18:18,2025-12-02 12:48,S1C_IW_GRDH_1SDV_20251202T124832_20251202T1248...,9.728797,IW,ASCENDING,C,"VV,VH",27,10,S1C_IW_GRDH_1SDV_20251202T124832_20251202T1248...,2,6
6,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-08 05:55,2025-12-08 00:25,S1A_IW_GRDH_1SDV_20251208T002514_20251208T0025...,56.733736,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251208T002514_20251208T0025...,2,3
7,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-08 05:55,2025-12-08 00:25,S1A_IW_GRDH_1SDV_20251208T002539_20251208T0026...,43.333318,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251208T002539_20251208T0026...,3,3
8,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-08 18:19,2025-12-08 12:49,S1A_IW_GRDH_1SDV_20251208T124915_20251208T1249...,6.686733,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251208T124915_20251208T1249...,1,3
9,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-08 18:19,2025-12-08 12:49,S1A_IW_GRDH_1SDV_20251208T124944_20251208T1250...,3.108311,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251208T124944_20251208T1250...,2,3
10,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-20 05:55,2025-12-20 00:25,S1A_IW_GRDH_1SDV_20251220T002512_20251220T0025...,56.707925,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251220T002512_20251220T0025...,2,3
11,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-20 05:55,2025-12-20 00:25,S1A_IW_GRDH_1SDV_20251220T002537_20251220T0026...,43.358778,IW,DESCENDING,A,"VV,VH",19,10,S1A_IW_GRDH_1SDV_20251220T002537_20251220T0026...,3,3
12,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-20 18:19,2025-12-20 12:49,S1A_IW_GRDH_1SDV_20251220T124913_20251220T1249...,6.544987,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251220T124913_20251220T1249...,1,3
13,EV2_Nov_2025,PP1_AOI_KELANI_01,2025-12-20 18:19,2025-12-20 12:49,S1A_IW_GRDH_1SDV_20251220T124942_20251220T1250...,3.085749,IW,ASCENDING,A,"VV,VH",27,10,S1A_IW_GRDH_1SDV_20251220T124942_20251220T1250...,2,3

## Saving the inventory

In [15]:
inventory_path = (
    "../shared/events/s1_scene_inventory_ev2_pp1_bt_mask_pilot.csv"
)

inventory_df.to_csv(
    inventory_path,
    index=False
)

print(
    f"Saved Sentinel-1 inventory to: {inventory_path}"
)

Saved Sentinel-1 inventory to: ../shared/events/s1_scene_inventory_ev2_pp1_bt_mask_pilot.csv